name: Full ROM Build with GitHub Release and Ccache

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'ROM Manifest URL'
        required: true
        default: 'https://github.com/LineageOS/android.git'
      MANIFEST_BRANCH:
        description: 'ROM Manifest Branch'
        required: true
        default: 'lineage-20.0'
        type: choice
        options:
          - lineage-20.0
          - lineage-19.1
      DEVICE_TREE:
        description: 'Device Tree repo URL'
        required: true
        default: 'https://github.com/Carckv2/new_water_dt.git'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'patch-1'
      VENDOR_TREE:
        description: 'Vendor Tree repo URL (optional)'
        required: false
        default: ''
      VENDOR_TREE_BRANCH:
        description: 'Vendor Tree Branch (optional)'
        required: false
        default: ''
      KERNEL_TREE:
        description: 'Kernel Tree repo URL (optional)'
        required: false
        default: ''
      KERNEL_TREE_BRANCH:
        description: 'Kernel Tree Branch (optional)'
        required: false
        default: ''
      DEVICE_CODENAME:
        description: 'Device Codename (e.g. nashc)'
        required: true
        default: 'water'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 10G
      CCACHE_COMPRESS: 1
      CCACHE_COMPRESSLEVEL: 6
      CCACHE_NOCOMPRESS: ''
      CCACHE_LOGFILE: ${{ github.workspace }}/ccache.log

    steps:
    - name: Setup Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex git gnupg gperf imagemagick lib32ncurses5-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop openjdk-11-jdk pngcrush repo rsync schedtool squashfs-tools xsltproc zip zlib1g-dev ccache

    - name: Setup repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
      # Add ~/bin to PATH immediately for all next steps
    - name: Add repo to PATH
      run: echo "$HOME/bin" >> $GITHUB_PATH

    - name: Initialize Repo Manifest
      run: |
        set -e
        mkdir -p $GITHUB_WORKSPACE/rom
        cd $GITHUB_WORKSPACE/rom
        repo init -u ${{ inputs.MANIFEST_URL }} -b ${{ inputs.MANIFEST_BRANCH }}

    - name: Sync Repo
      run: |
        set -e
        cd $GITHUB_WORKSPACE/rom
        repo sync -c -j$(nproc) --force-sync --no-clone-bundle --no-tags --verbose

    - name: Clone Device Tree
      run: |
        set -e
        cd $GITHUB_WORKSPACE/rom
        mkdir -p device/realme
        git clone -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_TREE }} device/realme/${{ inputs.DEVICE_CODENAME }}

    - name: Clone Vendor Tree (Optional)
      if: ${{ inputs.VENDOR_TREE != '' }}
      run: |
        set -e
        cd $GITHUB_WORKSPACE/rom
        mkdir -p vendor/realme
        git clone -b ${{ inputs.VENDOR_TREE_BRANCH }} ${{ inputs.VENDOR_TREE }} vendor/realme/${{ inputs.DEVICE_CODENAME }}

    - name: Clone Kernel Tree (Optional)
      if: ${{ inputs.KERNEL_TREE != '' }}
      run: |
        set -e
        cd $GITHUB_WORKSPACE/rom
        mkdir -p kernel/realme/${{ inputs.DEVICE_CODENAME }}
        git clone -b ${{ inputs.KERNEL_TREE_BRANCH }} ${{ inputs.KERNEL_TREE }} kernel/realme/${{ inputs.DEVICE_CODENAME }}

    - name: Cache ccache directory
      uses: actions/cache@v3
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ runner.os }}-ccache-${{ inputs.DEVICE_CODENAME }}-${{ inputs.MANIFEST_BRANCH }}-${{ hashFiles('**/device/**', '**/vendor/**', '**/kernel/**') }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ inputs.DEVICE_CODENAME }}-${{ inputs.MANIFEST_BRANCH }}-
          ${{ runner.os }}-ccache-${{ inputs.DEVICE_CODENAME }}-
          ${{ runner.os }}-ccache-

    - name: Configure ccache
      run: |
        ccache --max-size=${{ env.CCACHE_MAXSIZE }}
        ccache --show-stats

    - name: Setup Build Environment and Lunch
      run: |
        set -e
        cd $GITHUB_WORKSPACE/rom
        bash -c "source build/envsetup.sh && lunch lineage_${{ inputs.DEVICE_CODENAME }}-userdebug"

    - name: Build ROM
      run: |
        set -e
        cd $GITHUB_WORKSPACE/rom
        mka bacon -j$(nproc)

    - name: Show ccache stats after build
      run: |
        ccache --show-stats

    - name: Save Build Date and Device Codename to Env
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Manila date +%Y%m%d)" >> $GITHUB_ENV
        echo "DEVICE_CODENAME=${{ inputs.DEVICE_CODENAME }}" >> $GITHUB_ENV

    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ github.run_id }}
        path: ${{ github.workspace }}/ccache.log

    - name: Upload ROM to GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ${{ github.workspace }}/rom/out/target/product/${{ env.DEVICE_CODENAME }}/*.zip
          ${{ github.workspace }}/rom/out/target/product/${{ env.DEVICE_CODENAME }}/*.img
        name: "LineageOS ROM for ${{ env.DEVICE_CODENAME }} // ${{ env.BUILD_DATE }}"
        tag_name: ${{ github.run_id }}
        body: |
          ## LineageOS ROM Build - Unofficial
          Branch: ${{ inputs.MANIFEST_BRANCH }}
          Device: ${{ env.DEVICE_CODENAME }}
          Build Date: ${{ env.BUILD_DATE }}
